build:
    environment:
        php: '5.4.41'
    tests:
        before:
            - 'composer install'
        override:
            - 'make test'
            - 'vendor/phpspec/phpspec/bin/phpspec run'