filter:
    paths: ["src/*"]
    excluded_paths:
      - "bin/"
      - "spec/"

checks:
    php:
        code_rating: true
        duplication: true

build:
    environment:
        docker: true
    tests:
        override:
            - 'make unit'