filter:
    paths: ["src/*"]
    excluded_paths:
      - "bin/"
      - "spec/"

checks:
    php:
        code_rating: true
        duplication: true

build:
    environment:
        docker: true
    tests:
        override:
            - 'make dev'
            - 'make unit PHP_VERSION=php-7.1'
            - 'make unit PHP_VERSION=php-5.6'
            - 'make unit PHP_VERSION=php-5.5'
            - 'make integration PHP_VERSION=php-7.1'
            - 'make integration PHP_VERSION=php-5.6'
            - 'make integration PHP_VERSION=php-5.5'